meesf/RiskyGamesAndAgents

- src/Board.java
- src/Player.java
- src/RiskVisual.java
- src/Territory.java
includes a very minor refactoring
> Assign colors to players and report unit counts

- src/infomgmag/Board.java
- src/infomgmag/Bot.java
- src/infomgmag/CombatMove.java
- src/infomgmag/Continent.java
- src/infomgmag/Hand.java
- src/infomgmag/Human.java
- src/infomgmag/Objective.java
- src/infomgmag/Player.java
- src/infomgmag/Risk.java
- src/infomgmag/RiskVisual.java
- src/infomgmag/Territory.java
In proper java people use packages. We are people and this is proper java; Q.E.D.
> Add package declarations

- .idea/workspace.xml
- src/infomgmag/Board.java
- src/infomgmag/Bot.java
- src/infomgmag/Hand.java
- src/infomgmag/Risk.java
There are now wildcards in the hand of a player, and players can now receive cards (they did not before)
> wildcards and the players now actually receive cards

- src/infomgmag/Hand.java
- src/infomgmag/Risk.java
> Defeatplayer

- src/infomgmag/Bot.java
fixed bug where player fortifies a territory of another player.
> bug fix in fortify fase

- src/infomgmag/RandomBot.java
- src/infomgmag/Risk.java
> Rename Bot to RandomBot

- src/infomgmag/RiskVisual.java
> Fix attack animation for alaska vs. kamchatka

- src/infomgmag/Risk.java
- src/infomgmag/RiskVisual.java
> Add nonvisual option

- src/infomgmag/Board.java
- src/infomgmag/Human.java
- src/infomgmag/Player.java
- src/infomgmag/RandomBot.java
- src/infomgmag/Risk.java
> Fix and improve player colors

- src/infomgmag/Risk.java
- src/infomgmag/RiskVisual.java
This moves initialization to the constructor, rather than a unnecessary call to an unnecessary method. Initialization is the constructor's job so let it do its job and pray that it lets you do yours.
It also re-orders some variables in a more logical way.
It also renames `players` to something better.
> Minor Refactoring

- src/infomgmag/Board.java
- src/infomgmag/Continent.java
- src/infomgmag/Risk.java
changed all getmembers to getterritories
-close #88
> refactored getmembers

- src/infomgmag/mars/CountryAgent.java
- src/infomgmag/mars/Mars.java
Closes #104 - Decentralization of agent values
Closes #108 - Recalculation of agent values (this could have been its own branch but it builds on the previous commit)
> Decentralize agentValues and recalculate before deciding on attack

- src/infomgmag/mars/CountryAgent.java
- src/infomgmag/mars/Mars.java
- src/infomgmag/mars/ProbabilityGrid.java
> Refactor one-character constants

- src/infomgmag/mars/Mars.java
> Improve adjacent-territories calculation

- src/infomgmag/mars/CountryAgent.java
- src/infomgmag/mars/Mars.java
> Fix issue where zero reinforcements would break the agent

- src/infomgmag/Board.java
- src/infomgmag/Continent.java
- src/infomgmag/Territory.java
- src/infomgmag/mars/CountryAgent.java
> Changed names refactoring

- src/infomgmag/Player.java
- src/infomgmag/Risk.java
- src/infomgmag/mars/CountryAgent.java
- src/infomgmag/mars/Mars.java
Added bonuns for attacking country when not yet conquered country in that turn
closes #130
> Bonus for first country

- src/infomgmag/Risk.java
- src/infomgmag/mars/CountryAgent.java
- src/infomgmag/mars/Goal.java
It was the case that a country was valuated by using the owncontinent bonus (among other things). But it is better to use this in the valuation of a goal, since most of the times, a goal completes a continent, not only one country.
> Moved owning continent to goal

- src/infomgmag/mars/CountryAgent.java
> Fix what is seen as opponent/friendly in value calculation

- src/infomgmag/Risk.java
The seed is now printed. In case you see a bug, you can use the seed to reproduce the problem.
> Printing seed

- src/infomgmag/mars/CountryAgent.java
> Use correct weights for farmies

- src/infomgmag/Board.java
- src/infomgmag/Risk.java
- src/infomgmag/RiskVisual.java
> More visuals

- src/infomgmag/mars/CountryAgent.java
- src/infomgmag/mars/Personality.java
> Refactor personality

- src/infomgmag/Board.java
- src/infomgmag/CombatMove.java
- src/infomgmag/Continent.java
- src/infomgmag/Player.java
- src/infomgmag/RandomBot.java
- src/infomgmag/Risk.java
- src/infomgmag/RiskVisual.java
- src/infomgmag/Territory.java
- src/infomgmag/mars/CountryAgent.java
- src/infomgmag/mars/DefensiveBid.java
- src/infomgmag/mars/Goal.java
- src/infomgmag/mars/Mars.java
- src/infomgmag/mars/OffensiveBid.java
- src/infomgmag/mars/Personality.java
- src/infomgmag/mars/ReinforcementBid.java
- Fix 0 units bug (Closes #144)
- Add bonus for killing other player
- Remove unused code
- Remove unused imports
- Refactor `clearlists` -> `clearGoals` as clearing goals is what it does.
- Refactor `nUnits` to `units`, there's nothing wrong with using the name `units` to describe an integer.
- Take out `getValue`, there is no sense in having a private getter.
- Replace tabs by spaces where tabs where still used
- Rewrite some methods to be shorter and simpler using streams
- Refactor `nReinforcements` -> `reinforcements`, there's nothing wrong with using the name `reinforcements` to describe an integer.
- Change `Double` -> `double` where possible
- Change `Integer` -> `int` where possible
> Make Risk great again!

- src/infomgmag/Player.java
- src/infomgmag/RiskVisual.java
- src/infomgmag/mars/CountryAgent.java
- src/infomgmag/mars/Personality.java
- src/infomgmag/mars/PersonalityFactory.java
If the player has not yet conquered a territory yet, a bid will have a bonus. I have not added the bonus to the value of a country, because this will also influence the goal, since all countries in the goal will than have this bonus, which is not fair. close #155
> Added first country bonus to bid

- src/infomgmag/Risk.java
- src/infomgmag/RiskVisual.java
> Changed speed after initializing reinforcements

- src/infomgmag/Board.java
- src/infomgmag/Player.java
- src/infomgmag/RandomBot.java
- src/infomgmag/Risk.java
- src/infomgmag/mars/Mars.java
- src/infomgmag/mars/PersonalityFactory.java
The moving in after invasion now balances the number of units that are moved in, inspired by the fortifying move function.
> moving in after invasion

- src/infomgmag/Risk.java
- Fixed a typo in Risk.java (agressivePlayers --> aggressivePlayers)
- Game is initialized with the correct number of armies
> correct initial armies

- src/infomgmag/mars/Mars.java
> Move units equal to at least number of attacker dice thrown

- src/infomgmag/Board.java
- src/infomgmag/Continent.java
- src/infomgmag/RandomBot.java
- src/infomgmag/Risk.java
- src/infomgmag/RiskVisual.java
- src/infomgmag/Territory.java
- src/infomgmag/mars/CountryAgent.java
- src/infomgmag/mars/Mars.java
- Small style fixes
- Remove unnecessary whitespace
- Redo the setting of amount of continents bordered
- Add some comments on board construction
- Replace `printError` with `RuntimeException` throwing
- Refactor `addUnits` to not use the `Player` object
- Fix random moving in of units
> Improve style and add comments

- src/infomgmag/CombatEvent.java
- src/infomgmag/Result.java
- src/infomgmag/Risk.java
- src/infomgmag/Territory.java
- src/infomgmag/Tournament.java
- src/infomgmag/TurnLog.java
Created a tournament class that can run multiple games. In the console the results of the games are printed.
> working tournament

- src/infomgmag/Result.java
- src/infomgmag/Risk.java
- src/infomgmag/Tournament.java
Ive added the possibility to randomize the players each game in a tournament. All the stats is now based on the agent type (normal, aggressive etc) instead of the name of the player. I have also added a maximum amount of turn a game can take, since a game with only defensive agents will take forever.
> Random players

- src/infomgmag/Risk.java
- src/infomgmag/Tournament.java
- src/infomgmag/mars/CountryAgent.java
- src/infomgmag/mars/PersonalityFactory.java
This sets personalities to what we actually use
> Fix personalities
